
'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.ComponentModel
Imports System.Data.EntityClient
Imports System.Data.Objects
Imports System.Data.Objects.DataClasses
Imports System.Linq
Imports System.Runtime.Serialization
Imports System.Xml.Serialization


<Assembly: EdmSchemaAttribute("cb3946ba-253d-4d82-a52b-0b667de97ec4")>
#Region "EDM Relationship Metadata"
<Assembly: EdmRelationshipAttribute("MascotaModel", "FK__Adopcion__id_ado__29572725", "Adoptantes", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, GetType(Adoptantes), "Adopcion", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, GetType(Adopcion), True)>
<Assembly: EdmRelationshipAttribute("MascotaModel", "FK__Adopcion__usuari__2A4B4B5E", "Usuarios", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, GetType(Usuarios), "Adopcion", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, GetType(Adopcion), True)>
<Assembly: EdmRelationshipAttribute("MascotaModel", "FK__DetalleAd__id_ad__2F10007B", "Adopcion", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, GetType(Adopcion), "DetalleAdopcion", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, GetType(DetalleAdopcion), True)>
<Assembly: EdmRelationshipAttribute("MascotaModel", "FK__DetalleAd__id_ma__300424B4", "Mascotas", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, GetType(Mascotas), "DetalleAdopcion", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, GetType(DetalleAdopcion), True)>
<Assembly: EdmRelationshipAttribute("MascotaModel", "FK__Mascotas__id_esp__1B0907CE", "Especie", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, GetType(Especie), "Mascotas", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, GetType(Mascotas), True)>
<Assembly: EdmRelationshipAttribute("MascotaModel", "FK__Hogar__id_person__0DAF0CB0", "Personal", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, GetType(Personal), "Hogar", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, GetType(Hogar), True)>
<Assembly: EdmRelationshipAttribute("MascotaModel", "FK__Hogar__id_tipo_h__0EA330E9", "Tipo_hogar", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, GetType(Tipo_hogar), "Hogar", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, GetType(Hogar), True)>
<Assembly: EdmRelationshipAttribute("MascotaModel", "FK__Mascotas__id_hog__1CF15040", "Hogar", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, GetType(Hogar), "Mascotas", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, GetType(Mascotas), True)>
<Assembly: EdmRelationshipAttribute("MascotaModel", "FK__Mascotas__id_raz__1BFD2C07", "Raza", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, GetType(Raza), "Mascotas", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, GetType(Mascotas), True)>
<Assembly: EdmRelationshipAttribute("MascotaModel", "FK__Personal__id_tar__0519C6AF", "Tareas", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, GetType(Tareas), "Personal", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, GetType(Personal), True)>

#End Region

#Region "Contexts"

''' <summary>
''' No Metadata Documentation available.
''' </summary>
Public Partial Class MascotaEntities
    Inherits ObjectContext

    #Region "Constructors"

    ''' <summary>
    ''' Initializes a new MascotaEntities object using the connection string found in the 'MascotaEntities' section of the application configuration file.
    ''' </summary>
    Public Sub New()
        MyBase.New("name=MascotaEntities", "MascotaEntities")
        MyBase.ContextOptions.LazyLoadingEnabled = true
        OnContextCreated()
    End Sub

    ''' <summary>
    ''' Initialize a new MascotaEntities object.
    ''' </summary>
    Public Sub New(ByVal connectionString As String)
        MyBase.New(connectionString, "MascotaEntities")
        MyBase.ContextOptions.LazyLoadingEnabled = true
        OnContextCreated()
    End Sub

    ''' <summary>
    ''' Initialize a new MascotaEntities object.
    ''' </summary>
    Public Sub New(ByVal connection As EntityConnection)
        MyBase.New(connection, "MascotaEntities")
        MyBase.ContextOptions.LazyLoadingEnabled = true
        OnContextCreated()
    End Sub

    #End Region

    #Region "Partial Methods"

    Partial Private Sub OnContextCreated()
    End Sub

    #End Region

    #Region "ObjectSet Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public ReadOnly Property Adopcion() As ObjectSet(Of Adopcion)
        Get
            If (_Adopcion Is Nothing) Then
                _Adopcion = MyBase.CreateObjectSet(Of Adopcion)("Adopcion")
            End If
            Return _Adopcion
        End Get
    End Property

    Private _Adopcion As ObjectSet(Of Adopcion)

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public ReadOnly Property Adoptantes() As ObjectSet(Of Adoptantes)
        Get
            If (_Adoptantes Is Nothing) Then
                _Adoptantes = MyBase.CreateObjectSet(Of Adoptantes)("Adoptantes")
            End If
            Return _Adoptantes
        End Get
    End Property

    Private _Adoptantes As ObjectSet(Of Adoptantes)

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public ReadOnly Property DetalleAdopcion() As ObjectSet(Of DetalleAdopcion)
        Get
            If (_DetalleAdopcion Is Nothing) Then
                _DetalleAdopcion = MyBase.CreateObjectSet(Of DetalleAdopcion)("DetalleAdopcion")
            End If
            Return _DetalleAdopcion
        End Get
    End Property

    Private _DetalleAdopcion As ObjectSet(Of DetalleAdopcion)

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public ReadOnly Property Especie() As ObjectSet(Of Especie)
        Get
            If (_Especie Is Nothing) Then
                _Especie = MyBase.CreateObjectSet(Of Especie)("Especie")
            End If
            Return _Especie
        End Get
    End Property

    Private _Especie As ObjectSet(Of Especie)

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public ReadOnly Property Hogar() As ObjectSet(Of Hogar)
        Get
            If (_Hogar Is Nothing) Then
                _Hogar = MyBase.CreateObjectSet(Of Hogar)("Hogar")
            End If
            Return _Hogar
        End Get
    End Property

    Private _Hogar As ObjectSet(Of Hogar)

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public ReadOnly Property Mascotas() As ObjectSet(Of Mascotas)
        Get
            If (_Mascotas Is Nothing) Then
                _Mascotas = MyBase.CreateObjectSet(Of Mascotas)("Mascotas")
            End If
            Return _Mascotas
        End Get
    End Property

    Private _Mascotas As ObjectSet(Of Mascotas)

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public ReadOnly Property Personal() As ObjectSet(Of Personal)
        Get
            If (_Personal Is Nothing) Then
                _Personal = MyBase.CreateObjectSet(Of Personal)("Personal")
            End If
            Return _Personal
        End Get
    End Property

    Private _Personal As ObjectSet(Of Personal)

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public ReadOnly Property Raza() As ObjectSet(Of Raza)
        Get
            If (_Raza Is Nothing) Then
                _Raza = MyBase.CreateObjectSet(Of Raza)("Raza")
            End If
            Return _Raza
        End Get
    End Property

    Private _Raza As ObjectSet(Of Raza)

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public ReadOnly Property Tareas() As ObjectSet(Of Tareas)
        Get
            If (_Tareas Is Nothing) Then
                _Tareas = MyBase.CreateObjectSet(Of Tareas)("Tareas")
            End If
            Return _Tareas
        End Get
    End Property

    Private _Tareas As ObjectSet(Of Tareas)

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public ReadOnly Property Tipo_hogar() As ObjectSet(Of Tipo_hogar)
        Get
            If (_Tipo_hogar Is Nothing) Then
                _Tipo_hogar = MyBase.CreateObjectSet(Of Tipo_hogar)("Tipo_hogar")
            End If
            Return _Tipo_hogar
        End Get
    End Property

    Private _Tipo_hogar As ObjectSet(Of Tipo_hogar)

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public ReadOnly Property Usuarios() As ObjectSet(Of Usuarios)
        Get
            If (_Usuarios Is Nothing) Then
                _Usuarios = MyBase.CreateObjectSet(Of Usuarios)("Usuarios")
            End If
            Return _Usuarios
        End Get
    End Property

    Private _Usuarios As ObjectSet(Of Usuarios)

    #End Region

    #Region "AddTo Methods"

    ''' <summary>
    ''' Deprecated Method for adding a new object to the Adopcion EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
    ''' </summary>
    Public Sub AddToAdopcion(ByVal adopcion As Adopcion)
        MyBase.AddObject("Adopcion", adopcion)
    End Sub

    ''' <summary>
    ''' Deprecated Method for adding a new object to the Adoptantes EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
    ''' </summary>
    Public Sub AddToAdoptantes(ByVal adoptantes As Adoptantes)
        MyBase.AddObject("Adoptantes", adoptantes)
    End Sub

    ''' <summary>
    ''' Deprecated Method for adding a new object to the DetalleAdopcion EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
    ''' </summary>
    Public Sub AddToDetalleAdopcion(ByVal detalleAdopcion As DetalleAdopcion)
        MyBase.AddObject("DetalleAdopcion", detalleAdopcion)
    End Sub

    ''' <summary>
    ''' Deprecated Method for adding a new object to the Especie EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
    ''' </summary>
    Public Sub AddToEspecie(ByVal especie As Especie)
        MyBase.AddObject("Especie", especie)
    End Sub

    ''' <summary>
    ''' Deprecated Method for adding a new object to the Hogar EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
    ''' </summary>
    Public Sub AddToHogar(ByVal hogar As Hogar)
        MyBase.AddObject("Hogar", hogar)
    End Sub

    ''' <summary>
    ''' Deprecated Method for adding a new object to the Mascotas EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
    ''' </summary>
    Public Sub AddToMascotas(ByVal mascotas As Mascotas)
        MyBase.AddObject("Mascotas", mascotas)
    End Sub

    ''' <summary>
    ''' Deprecated Method for adding a new object to the Personal EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
    ''' </summary>
    Public Sub AddToPersonal(ByVal personal As Personal)
        MyBase.AddObject("Personal", personal)
    End Sub

    ''' <summary>
    ''' Deprecated Method for adding a new object to the Raza EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
    ''' </summary>
    Public Sub AddToRaza(ByVal raza As Raza)
        MyBase.AddObject("Raza", raza)
    End Sub

    ''' <summary>
    ''' Deprecated Method for adding a new object to the Tareas EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
    ''' </summary>
    Public Sub AddToTareas(ByVal tareas As Tareas)
        MyBase.AddObject("Tareas", tareas)
    End Sub

    ''' <summary>
    ''' Deprecated Method for adding a new object to the Tipo_hogar EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
    ''' </summary>
    Public Sub AddToTipo_hogar(ByVal tipo_hogar As Tipo_hogar)
        MyBase.AddObject("Tipo_hogar", tipo_hogar)
    End Sub

    ''' <summary>
    ''' Deprecated Method for adding a new object to the Usuarios EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
    ''' </summary>
    Public Sub AddToUsuarios(ByVal usuarios As Usuarios)
        MyBase.AddObject("Usuarios", usuarios)
    End Sub

    #End Region

End Class

#End Region

#Region "Entities"

''' <summary>
''' No Metadata Documentation available.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="MascotaModel", Name:="Adopcion")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class Adopcion
    Inherits EntityObject
    #Region "Factory Method"

    ''' <summary>
    ''' Create a new Adopcion object.
    ''' </summary>
    ''' <param name="id_adopcion">Initial value of the id_adopcion property.</param>
    Public Shared Function CreateAdopcion(id_adopcion As Global.System.Int32) As Adopcion
        Dim adopcion as Adopcion = New Adopcion
        adopcion.id_adopcion = id_adopcion
        Return adopcion
    End Function

    #End Region

    #Region "Primitive Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property id_adopcion() As Global.System.Int32
        Get
            Return _id_adopcion
        End Get
        Set
            If (_id_adopcion <> Value) Then
                Onid_adopcionChanging(value)
                ReportPropertyChanging("id_adopcion")
                _id_adopcion = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("id_adopcion")
                Onid_adopcionChanged()
            End If
        End Set
    End Property

    Private _id_adopcion As Global.System.Int32
    Private Partial Sub Onid_adopcionChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub Onid_adopcionChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property id_adoptante() As Nullable(Of Global.System.Int32)
        Get
            Return _id_adoptante
        End Get
        Set
            Onid_adoptanteChanging(value)
            ReportPropertyChanging("id_adoptante")
            _id_adoptante = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("id_adoptante")
            Onid_adoptanteChanged()
        End Set
    End Property

    Private _id_adoptante As Nullable(Of Global.System.Int32)
    Private Partial Sub Onid_adoptanteChanging(value As Nullable(Of Global.System.Int32))
    End Sub

    Private Partial Sub Onid_adoptanteChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property fecha_adopcion() As Nullable(Of Global.System.DateTime)
        Get
            Return _fecha_adopcion
        End Get
        Set
            Onfecha_adopcionChanging(value)
            ReportPropertyChanging("fecha_adopcion")
            _fecha_adopcion = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("fecha_adopcion")
            Onfecha_adopcionChanged()
        End Set
    End Property

    Private _fecha_adopcion As Nullable(Of Global.System.DateTime)
    Private Partial Sub Onfecha_adopcionChanging(value As Nullable(Of Global.System.DateTime))
    End Sub

    Private Partial Sub Onfecha_adopcionChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property usuario() As Global.System.String
        Get
            Return _usuario
        End Get
        Set
            OnusuarioChanging(value)
            ReportPropertyChanging("usuario")
            _usuario = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("usuario")
            OnusuarioChanged()
        End Set
    End Property

    Private _usuario As Global.System.String
    Private Partial Sub OnusuarioChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnusuarioChanged()
    End Sub

    #End Region

    #Region "Navigation Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("MascotaModel", "FK__Adopcion__id_ado__29572725", "Adoptantes")>
    Public Property Adoptantes() As Adoptantes
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Adoptantes)("MascotaModel.FK__Adopcion__id_ado__29572725", "Adoptantes").Value
        End Get
        Set
            CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Adoptantes)("MascotaModel.FK__Adopcion__id_ado__29572725", "Adoptantes").Value = value
        End Set
    End Property
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <BrowsableAttribute(False)>
    <DataMemberAttribute()>
    Public Property AdoptantesReference() As EntityReference(Of Adoptantes)
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Adoptantes)("MascotaModel.FK__Adopcion__id_ado__29572725", "Adoptantes")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedReference(Of Adoptantes)("MascotaModel.FK__Adopcion__id_ado__29572725", "Adoptantes", value)
            End If
        End Set
    End Property

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("MascotaModel", "FK__Adopcion__usuari__2A4B4B5E", "Usuarios")>
    Public Property Usuarios() As Usuarios
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Usuarios)("MascotaModel.FK__Adopcion__usuari__2A4B4B5E", "Usuarios").Value
        End Get
        Set
            CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Usuarios)("MascotaModel.FK__Adopcion__usuari__2A4B4B5E", "Usuarios").Value = value
        End Set
    End Property
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <BrowsableAttribute(False)>
    <DataMemberAttribute()>
    Public Property UsuariosReference() As EntityReference(Of Usuarios)
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Usuarios)("MascotaModel.FK__Adopcion__usuari__2A4B4B5E", "Usuarios")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedReference(Of Usuarios)("MascotaModel.FK__Adopcion__usuari__2A4B4B5E", "Usuarios", value)
            End If
        End Set
    End Property

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("MascotaModel", "FK__DetalleAd__id_ad__2F10007B", "DetalleAdopcion")>
     Public Property DetalleAdopcion() As EntityCollection(Of DetalleAdopcion)
        Get
            Return CType(Me,IEntityWithRelationships).RelationshipManager.GetRelatedCollection(Of DetalleAdopcion)("MascotaModel.FK__DetalleAd__id_ad__2F10007B", "DetalleAdopcion")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedCollection(Of DetalleAdopcion)("MascotaModel.FK__DetalleAd__id_ad__2F10007B", "DetalleAdopcion", value)
            End If
        End Set
    End Property

    #End Region

End Class

''' <summary>
''' No Metadata Documentation available.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="MascotaModel", Name:="Adoptantes")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class Adoptantes
    Inherits EntityObject
    #Region "Factory Method"

    ''' <summary>
    ''' Create a new Adoptantes object.
    ''' </summary>
    ''' <param name="id_adoptante">Initial value of the id_adoptante property.</param>
    Public Shared Function CreateAdoptantes(id_adoptante As Global.System.Int32) As Adoptantes
        Dim adoptantes as Adoptantes = New Adoptantes
        adoptantes.id_adoptante = id_adoptante
        Return adoptantes
    End Function

    #End Region

    #Region "Primitive Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property id_adoptante() As Global.System.Int32
        Get
            Return _id_adoptante
        End Get
        Set
            If (_id_adoptante <> Value) Then
                Onid_adoptanteChanging(value)
                ReportPropertyChanging("id_adoptante")
                _id_adoptante = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("id_adoptante")
                Onid_adoptanteChanged()
            End If
        End Set
    End Property

    Private _id_adoptante As Global.System.Int32
    Private Partial Sub Onid_adoptanteChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub Onid_adoptanteChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property apellido() As Global.System.String
        Get
            Return _apellido
        End Get
        Set
            OnapellidoChanging(value)
            ReportPropertyChanging("apellido")
            _apellido = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("apellido")
            OnapellidoChanged()
        End Set
    End Property

    Private _apellido As Global.System.String
    Private Partial Sub OnapellidoChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnapellidoChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property nombre() As Global.System.String
        Get
            Return _nombre
        End Get
        Set
            OnnombreChanging(value)
            ReportPropertyChanging("nombre")
            _nombre = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("nombre")
            OnnombreChanged()
        End Set
    End Property

    Private _nombre As Global.System.String
    Private Partial Sub OnnombreChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnnombreChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property dni() As Nullable(Of Global.System.Int32)
        Get
            Return _dni
        End Get
        Set
            OndniChanging(value)
            ReportPropertyChanging("dni")
            _dni = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("dni")
            OndniChanged()
        End Set
    End Property

    Private _dni As Nullable(Of Global.System.Int32)
    Private Partial Sub OndniChanging(value As Nullable(Of Global.System.Int32))
    End Sub

    Private Partial Sub OndniChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property direccion() As Global.System.String
        Get
            Return _direccion
        End Get
        Set
            OndireccionChanging(value)
            ReportPropertyChanging("direccion")
            _direccion = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("direccion")
            OndireccionChanged()
        End Set
    End Property

    Private _direccion As Global.System.String
    Private Partial Sub OndireccionChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OndireccionChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property email() As Global.System.String
        Get
            Return _email
        End Get
        Set
            OnemailChanging(value)
            ReportPropertyChanging("email")
            _email = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("email")
            OnemailChanged()
        End Set
    End Property

    Private _email As Global.System.String
    Private Partial Sub OnemailChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnemailChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property telefono() As Global.System.String
        Get
            Return _telefono
        End Get
        Set
            OntelefonoChanging(value)
            ReportPropertyChanging("telefono")
            _telefono = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("telefono")
            OntelefonoChanged()
        End Set
    End Property

    Private _telefono As Global.System.String
    Private Partial Sub OntelefonoChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OntelefonoChanged()
    End Sub

    #End Region

    #Region "Navigation Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("MascotaModel", "FK__Adopcion__id_ado__29572725", "Adopcion")>
     Public Property Adopcion() As EntityCollection(Of Adopcion)
        Get
            Return CType(Me,IEntityWithRelationships).RelationshipManager.GetRelatedCollection(Of Adopcion)("MascotaModel.FK__Adopcion__id_ado__29572725", "Adopcion")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedCollection(Of Adopcion)("MascotaModel.FK__Adopcion__id_ado__29572725", "Adopcion", value)
            End If
        End Set
    End Property

    #End Region

End Class

''' <summary>
''' No Metadata Documentation available.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="MascotaModel", Name:="DetalleAdopcion")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class DetalleAdopcion
    Inherits EntityObject
    #Region "Factory Method"

    ''' <summary>
    ''' Create a new DetalleAdopcion object.
    ''' </summary>
    ''' <param name="id_detalle">Initial value of the id_detalle property.</param>
    Public Shared Function CreateDetalleAdopcion(id_detalle As Global.System.Int32) As DetalleAdopcion
        Dim detalleAdopcion as DetalleAdopcion = New DetalleAdopcion
        detalleAdopcion.id_detalle = id_detalle
        Return detalleAdopcion
    End Function

    #End Region

    #Region "Primitive Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property id_detalle() As Global.System.Int32
        Get
            Return _id_detalle
        End Get
        Set
            If (_id_detalle <> Value) Then
                Onid_detalleChanging(value)
                ReportPropertyChanging("id_detalle")
                _id_detalle = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("id_detalle")
                Onid_detalleChanged()
            End If
        End Set
    End Property

    Private _id_detalle As Global.System.Int32
    Private Partial Sub Onid_detalleChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub Onid_detalleChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property id_adopcion() As Nullable(Of Global.System.Int32)
        Get
            Return _id_adopcion
        End Get
        Set
            Onid_adopcionChanging(value)
            ReportPropertyChanging("id_adopcion")
            _id_adopcion = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("id_adopcion")
            Onid_adopcionChanged()
        End Set
    End Property

    Private _id_adopcion As Nullable(Of Global.System.Int32)
    Private Partial Sub Onid_adopcionChanging(value As Nullable(Of Global.System.Int32))
    End Sub

    Private Partial Sub Onid_adopcionChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property id_mascota() As Nullable(Of Global.System.Int32)
        Get
            Return _id_mascota
        End Get
        Set
            Onid_mascotaChanging(value)
            ReportPropertyChanging("id_mascota")
            _id_mascota = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("id_mascota")
            Onid_mascotaChanged()
        End Set
    End Property

    Private _id_mascota As Nullable(Of Global.System.Int32)
    Private Partial Sub Onid_mascotaChanging(value As Nullable(Of Global.System.Int32))
    End Sub

    Private Partial Sub Onid_mascotaChanged()
    End Sub

    #End Region

    #Region "Navigation Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("MascotaModel", "FK__DetalleAd__id_ad__2F10007B", "Adopcion")>
    Public Property Adopcion() As Adopcion
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Adopcion)("MascotaModel.FK__DetalleAd__id_ad__2F10007B", "Adopcion").Value
        End Get
        Set
            CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Adopcion)("MascotaModel.FK__DetalleAd__id_ad__2F10007B", "Adopcion").Value = value
        End Set
    End Property
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <BrowsableAttribute(False)>
    <DataMemberAttribute()>
    Public Property AdopcionReference() As EntityReference(Of Adopcion)
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Adopcion)("MascotaModel.FK__DetalleAd__id_ad__2F10007B", "Adopcion")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedReference(Of Adopcion)("MascotaModel.FK__DetalleAd__id_ad__2F10007B", "Adopcion", value)
            End If
        End Set
    End Property

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("MascotaModel", "FK__DetalleAd__id_ma__300424B4", "Mascotas")>
    Public Property Mascotas() As Mascotas
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Mascotas)("MascotaModel.FK__DetalleAd__id_ma__300424B4", "Mascotas").Value
        End Get
        Set
            CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Mascotas)("MascotaModel.FK__DetalleAd__id_ma__300424B4", "Mascotas").Value = value
        End Set
    End Property
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <BrowsableAttribute(False)>
    <DataMemberAttribute()>
    Public Property MascotasReference() As EntityReference(Of Mascotas)
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Mascotas)("MascotaModel.FK__DetalleAd__id_ma__300424B4", "Mascotas")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedReference(Of Mascotas)("MascotaModel.FK__DetalleAd__id_ma__300424B4", "Mascotas", value)
            End If
        End Set
    End Property

    #End Region

End Class

''' <summary>
''' No Metadata Documentation available.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="MascotaModel", Name:="Especie")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class Especie
    Inherits EntityObject
    #Region "Factory Method"

    ''' <summary>
    ''' Create a new Especie object.
    ''' </summary>
    ''' <param name="id_especie">Initial value of the id_especie property.</param>
    Public Shared Function CreateEspecie(id_especie As Global.System.Int32) As Especie
        Dim especie as Especie = New Especie
        especie.id_especie = id_especie
        Return especie
    End Function

    #End Region

    #Region "Primitive Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property id_especie() As Global.System.Int32
        Get
            Return _id_especie
        End Get
        Set
            If (_id_especie <> Value) Then
                Onid_especieChanging(value)
                ReportPropertyChanging("id_especie")
                _id_especie = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("id_especie")
                Onid_especieChanged()
            End If
        End Set
    End Property

    Private _id_especie As Global.System.Int32
    Private Partial Sub Onid_especieChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub Onid_especieChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property descripcion() As Global.System.String
        Get
            Return _descripcion
        End Get
        Set
            OndescripcionChanging(value)
            ReportPropertyChanging("descripcion")
            _descripcion = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("descripcion")
            OndescripcionChanged()
        End Set
    End Property

    Private _descripcion As Global.System.String
    Private Partial Sub OndescripcionChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OndescripcionChanged()
    End Sub

    #End Region

    #Region "Navigation Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("MascotaModel", "FK__Mascotas__id_esp__1B0907CE", "Mascotas")>
     Public Property Mascotas() As EntityCollection(Of Mascotas)
        Get
            Return CType(Me,IEntityWithRelationships).RelationshipManager.GetRelatedCollection(Of Mascotas)("MascotaModel.FK__Mascotas__id_esp__1B0907CE", "Mascotas")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedCollection(Of Mascotas)("MascotaModel.FK__Mascotas__id_esp__1B0907CE", "Mascotas", value)
            End If
        End Set
    End Property

    #End Region

End Class

''' <summary>
''' No Metadata Documentation available.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="MascotaModel", Name:="Hogar")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class Hogar
    Inherits EntityObject
    #Region "Factory Method"

    ''' <summary>
    ''' Create a new Hogar object.
    ''' </summary>
    ''' <param name="id_hogar">Initial value of the id_hogar property.</param>
    Public Shared Function CreateHogar(id_hogar As Global.System.Int32) As Hogar
        Dim hogar as Hogar = New Hogar
        hogar.id_hogar = id_hogar
        Return hogar
    End Function

    #End Region

    #Region "Primitive Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property id_hogar() As Global.System.Int32
        Get
            Return _id_hogar
        End Get
        Set
            If (_id_hogar <> Value) Then
                Onid_hogarChanging(value)
                ReportPropertyChanging("id_hogar")
                _id_hogar = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("id_hogar")
                Onid_hogarChanged()
            End If
        End Set
    End Property

    Private _id_hogar As Global.System.Int32
    Private Partial Sub Onid_hogarChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub Onid_hogarChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property nombre() As Global.System.String
        Get
            Return _nombre
        End Get
        Set
            OnnombreChanging(value)
            ReportPropertyChanging("nombre")
            _nombre = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("nombre")
            OnnombreChanged()
        End Set
    End Property

    Private _nombre As Global.System.String
    Private Partial Sub OnnombreChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnnombreChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property direccion() As Global.System.String
        Get
            Return _direccion
        End Get
        Set
            OndireccionChanging(value)
            ReportPropertyChanging("direccion")
            _direccion = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("direccion")
            OndireccionChanged()
        End Set
    End Property

    Private _direccion As Global.System.String
    Private Partial Sub OndireccionChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OndireccionChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property telefono() As Global.System.String
        Get
            Return _telefono
        End Get
        Set
            OntelefonoChanging(value)
            ReportPropertyChanging("telefono")
            _telefono = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("telefono")
            OntelefonoChanged()
        End Set
    End Property

    Private _telefono As Global.System.String
    Private Partial Sub OntelefonoChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OntelefonoChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property id_personal() As Nullable(Of Global.System.Int32)
        Get
            Return _id_personal
        End Get
        Set
            Onid_personalChanging(value)
            ReportPropertyChanging("id_personal")
            _id_personal = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("id_personal")
            Onid_personalChanged()
        End Set
    End Property

    Private _id_personal As Nullable(Of Global.System.Int32)
    Private Partial Sub Onid_personalChanging(value As Nullable(Of Global.System.Int32))
    End Sub

    Private Partial Sub Onid_personalChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property id_tipo_hogar() As Nullable(Of Global.System.Int32)
        Get
            Return _id_tipo_hogar
        End Get
        Set
            Onid_tipo_hogarChanging(value)
            ReportPropertyChanging("id_tipo_hogar")
            _id_tipo_hogar = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("id_tipo_hogar")
            Onid_tipo_hogarChanged()
        End Set
    End Property

    Private _id_tipo_hogar As Nullable(Of Global.System.Int32)
    Private Partial Sub Onid_tipo_hogarChanging(value As Nullable(Of Global.System.Int32))
    End Sub

    Private Partial Sub Onid_tipo_hogarChanged()
    End Sub

    #End Region

    #Region "Navigation Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("MascotaModel", "FK__Hogar__id_person__0DAF0CB0", "Personal")>
    Public Property Personal() As Personal
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Personal)("MascotaModel.FK__Hogar__id_person__0DAF0CB0", "Personal").Value
        End Get
        Set
            CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Personal)("MascotaModel.FK__Hogar__id_person__0DAF0CB0", "Personal").Value = value
        End Set
    End Property
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <BrowsableAttribute(False)>
    <DataMemberAttribute()>
    Public Property PersonalReference() As EntityReference(Of Personal)
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Personal)("MascotaModel.FK__Hogar__id_person__0DAF0CB0", "Personal")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedReference(Of Personal)("MascotaModel.FK__Hogar__id_person__0DAF0CB0", "Personal", value)
            End If
        End Set
    End Property

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("MascotaModel", "FK__Hogar__id_tipo_h__0EA330E9", "Tipo_hogar")>
    Public Property Tipo_hogar() As Tipo_hogar
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Tipo_hogar)("MascotaModel.FK__Hogar__id_tipo_h__0EA330E9", "Tipo_hogar").Value
        End Get
        Set
            CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Tipo_hogar)("MascotaModel.FK__Hogar__id_tipo_h__0EA330E9", "Tipo_hogar").Value = value
        End Set
    End Property
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <BrowsableAttribute(False)>
    <DataMemberAttribute()>
    Public Property Tipo_hogarReference() As EntityReference(Of Tipo_hogar)
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Tipo_hogar)("MascotaModel.FK__Hogar__id_tipo_h__0EA330E9", "Tipo_hogar")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedReference(Of Tipo_hogar)("MascotaModel.FK__Hogar__id_tipo_h__0EA330E9", "Tipo_hogar", value)
            End If
        End Set
    End Property

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("MascotaModel", "FK__Mascotas__id_hog__1CF15040", "Mascotas")>
     Public Property Mascotas() As EntityCollection(Of Mascotas)
        Get
            Return CType(Me,IEntityWithRelationships).RelationshipManager.GetRelatedCollection(Of Mascotas)("MascotaModel.FK__Mascotas__id_hog__1CF15040", "Mascotas")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedCollection(Of Mascotas)("MascotaModel.FK__Mascotas__id_hog__1CF15040", "Mascotas", value)
            End If
        End Set
    End Property

    #End Region

End Class

''' <summary>
''' No Metadata Documentation available.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="MascotaModel", Name:="Mascotas")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class Mascotas
    Inherits EntityObject
    #Region "Factory Method"

    ''' <summary>
    ''' Create a new Mascotas object.
    ''' </summary>
    ''' <param name="id_mascota">Initial value of the id_mascota property.</param>
    Public Shared Function CreateMascotas(id_mascota As Global.System.Int32) As Mascotas
        Dim mascotas as Mascotas = New Mascotas
        mascotas.id_mascota = id_mascota
        Return mascotas
    End Function

    #End Region

    #Region "Primitive Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property id_mascota() As Global.System.Int32
        Get
            Return _id_mascota
        End Get
        Set
            If (_id_mascota <> Value) Then
                Onid_mascotaChanging(value)
                ReportPropertyChanging("id_mascota")
                _id_mascota = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("id_mascota")
                Onid_mascotaChanged()
            End If
        End Set
    End Property

    Private _id_mascota As Global.System.Int32
    Private Partial Sub Onid_mascotaChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub Onid_mascotaChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property nombre() As Global.System.String
        Get
            Return _nombre
        End Get
        Set
            OnnombreChanging(value)
            ReportPropertyChanging("nombre")
            _nombre = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("nombre")
            OnnombreChanged()
        End Set
    End Property

    Private _nombre As Global.System.String
    Private Partial Sub OnnombreChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnnombreChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property sexo() As Global.System.String
        Get
            Return _sexo
        End Get
        Set
            OnsexoChanging(value)
            ReportPropertyChanging("sexo")
            _sexo = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("sexo")
            OnsexoChanged()
        End Set
    End Property

    Private _sexo As Global.System.String
    Private Partial Sub OnsexoChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnsexoChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property id_especie() As Nullable(Of Global.System.Int32)
        Get
            Return _id_especie
        End Get
        Set
            Onid_especieChanging(value)
            ReportPropertyChanging("id_especie")
            _id_especie = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("id_especie")
            Onid_especieChanged()
        End Set
    End Property

    Private _id_especie As Nullable(Of Global.System.Int32)
    Private Partial Sub Onid_especieChanging(value As Nullable(Of Global.System.Int32))
    End Sub

    Private Partial Sub Onid_especieChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property id_raza() As Nullable(Of Global.System.Int32)
        Get
            Return _id_raza
        End Get
        Set
            Onid_razaChanging(value)
            ReportPropertyChanging("id_raza")
            _id_raza = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("id_raza")
            Onid_razaChanged()
        End Set
    End Property

    Private _id_raza As Nullable(Of Global.System.Int32)
    Private Partial Sub Onid_razaChanging(value As Nullable(Of Global.System.Int32))
    End Sub

    Private Partial Sub Onid_razaChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property color() As Global.System.String
        Get
            Return _color
        End Get
        Set
            OncolorChanging(value)
            ReportPropertyChanging("color")
            _color = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("color")
            OncolorChanged()
        End Set
    End Property

    Private _color As Global.System.String
    Private Partial Sub OncolorChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OncolorChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property id_hogar() As Nullable(Of Global.System.Int32)
        Get
            Return _id_hogar
        End Get
        Set
            Onid_hogarChanging(value)
            ReportPropertyChanging("id_hogar")
            _id_hogar = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("id_hogar")
            Onid_hogarChanged()
        End Set
    End Property

    Private _id_hogar As Nullable(Of Global.System.Int32)
    Private Partial Sub Onid_hogarChanging(value As Nullable(Of Global.System.Int32))
    End Sub

    Private Partial Sub Onid_hogarChanged()
    End Sub

    #End Region

    #Region "Navigation Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("MascotaModel", "FK__DetalleAd__id_ma__300424B4", "DetalleAdopcion")>
     Public Property DetalleAdopcion() As EntityCollection(Of DetalleAdopcion)
        Get
            Return CType(Me,IEntityWithRelationships).RelationshipManager.GetRelatedCollection(Of DetalleAdopcion)("MascotaModel.FK__DetalleAd__id_ma__300424B4", "DetalleAdopcion")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedCollection(Of DetalleAdopcion)("MascotaModel.FK__DetalleAd__id_ma__300424B4", "DetalleAdopcion", value)
            End If
        End Set
    End Property

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("MascotaModel", "FK__Mascotas__id_esp__1B0907CE", "Especie")>
    Public Property Especie() As Especie
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Especie)("MascotaModel.FK__Mascotas__id_esp__1B0907CE", "Especie").Value
        End Get
        Set
            CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Especie)("MascotaModel.FK__Mascotas__id_esp__1B0907CE", "Especie").Value = value
        End Set
    End Property
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <BrowsableAttribute(False)>
    <DataMemberAttribute()>
    Public Property EspecieReference() As EntityReference(Of Especie)
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Especie)("MascotaModel.FK__Mascotas__id_esp__1B0907CE", "Especie")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedReference(Of Especie)("MascotaModel.FK__Mascotas__id_esp__1B0907CE", "Especie", value)
            End If
        End Set
    End Property

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("MascotaModel", "FK__Mascotas__id_hog__1CF15040", "Hogar")>
    Public Property Hogar() As Hogar
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Hogar)("MascotaModel.FK__Mascotas__id_hog__1CF15040", "Hogar").Value
        End Get
        Set
            CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Hogar)("MascotaModel.FK__Mascotas__id_hog__1CF15040", "Hogar").Value = value
        End Set
    End Property
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <BrowsableAttribute(False)>
    <DataMemberAttribute()>
    Public Property HogarReference() As EntityReference(Of Hogar)
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Hogar)("MascotaModel.FK__Mascotas__id_hog__1CF15040", "Hogar")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedReference(Of Hogar)("MascotaModel.FK__Mascotas__id_hog__1CF15040", "Hogar", value)
            End If
        End Set
    End Property

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("MascotaModel", "FK__Mascotas__id_raz__1BFD2C07", "Raza")>
    Public Property Raza() As Raza
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Raza)("MascotaModel.FK__Mascotas__id_raz__1BFD2C07", "Raza").Value
        End Get
        Set
            CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Raza)("MascotaModel.FK__Mascotas__id_raz__1BFD2C07", "Raza").Value = value
        End Set
    End Property
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <BrowsableAttribute(False)>
    <DataMemberAttribute()>
    Public Property RazaReference() As EntityReference(Of Raza)
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Raza)("MascotaModel.FK__Mascotas__id_raz__1BFD2C07", "Raza")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedReference(Of Raza)("MascotaModel.FK__Mascotas__id_raz__1BFD2C07", "Raza", value)
            End If
        End Set
    End Property

    #End Region

End Class

''' <summary>
''' No Metadata Documentation available.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="MascotaModel", Name:="Personal")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class Personal
    Inherits EntityObject
    #Region "Factory Method"

    ''' <summary>
    ''' Create a new Personal object.
    ''' </summary>
    ''' <param name="id_personal">Initial value of the id_personal property.</param>
    Public Shared Function CreatePersonal(id_personal As Global.System.Int32) As Personal
        Dim personal as Personal = New Personal
        personal.id_personal = id_personal
        Return personal
    End Function

    #End Region

    #Region "Primitive Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property id_personal() As Global.System.Int32
        Get
            Return _id_personal
        End Get
        Set
            If (_id_personal <> Value) Then
                Onid_personalChanging(value)
                ReportPropertyChanging("id_personal")
                _id_personal = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("id_personal")
                Onid_personalChanged()
            End If
        End Set
    End Property

    Private _id_personal As Global.System.Int32
    Private Partial Sub Onid_personalChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub Onid_personalChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property apellido() As Global.System.String
        Get
            Return _apellido
        End Get
        Set
            OnapellidoChanging(value)
            ReportPropertyChanging("apellido")
            _apellido = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("apellido")
            OnapellidoChanged()
        End Set
    End Property

    Private _apellido As Global.System.String
    Private Partial Sub OnapellidoChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnapellidoChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property nombre() As Global.System.String
        Get
            Return _nombre
        End Get
        Set
            OnnombreChanging(value)
            ReportPropertyChanging("nombre")
            _nombre = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("nombre")
            OnnombreChanged()
        End Set
    End Property

    Private _nombre As Global.System.String
    Private Partial Sub OnnombreChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnnombreChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property dni() As Nullable(Of Global.System.Int32)
        Get
            Return _dni
        End Get
        Set
            OndniChanging(value)
            ReportPropertyChanging("dni")
            _dni = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("dni")
            OndniChanged()
        End Set
    End Property

    Private _dni As Nullable(Of Global.System.Int32)
    Private Partial Sub OndniChanging(value As Nullable(Of Global.System.Int32))
    End Sub

    Private Partial Sub OndniChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property direccion() As Global.System.String
        Get
            Return _direccion
        End Get
        Set
            OndireccionChanging(value)
            ReportPropertyChanging("direccion")
            _direccion = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("direccion")
            OndireccionChanged()
        End Set
    End Property

    Private _direccion As Global.System.String
    Private Partial Sub OndireccionChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OndireccionChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property email() As Global.System.String
        Get
            Return _email
        End Get
        Set
            OnemailChanging(value)
            ReportPropertyChanging("email")
            _email = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("email")
            OnemailChanged()
        End Set
    End Property

    Private _email As Global.System.String
    Private Partial Sub OnemailChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnemailChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property telefono() As Global.System.String
        Get
            Return _telefono
        End Get
        Set
            OntelefonoChanging(value)
            ReportPropertyChanging("telefono")
            _telefono = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("telefono")
            OntelefonoChanged()
        End Set
    End Property

    Private _telefono As Global.System.String
    Private Partial Sub OntelefonoChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OntelefonoChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property id_tarea() As Nullable(Of Global.System.Int32)
        Get
            Return _id_tarea
        End Get
        Set
            Onid_tareaChanging(value)
            ReportPropertyChanging("id_tarea")
            _id_tarea = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("id_tarea")
            Onid_tareaChanged()
        End Set
    End Property

    Private _id_tarea As Nullable(Of Global.System.Int32)
    Private Partial Sub Onid_tareaChanging(value As Nullable(Of Global.System.Int32))
    End Sub

    Private Partial Sub Onid_tareaChanged()
    End Sub

    #End Region

    #Region "Navigation Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("MascotaModel", "FK__Hogar__id_person__0DAF0CB0", "Hogar")>
     Public Property Hogar() As EntityCollection(Of Hogar)
        Get
            Return CType(Me,IEntityWithRelationships).RelationshipManager.GetRelatedCollection(Of Hogar)("MascotaModel.FK__Hogar__id_person__0DAF0CB0", "Hogar")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedCollection(Of Hogar)("MascotaModel.FK__Hogar__id_person__0DAF0CB0", "Hogar", value)
            End If
        End Set
    End Property

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("MascotaModel", "FK__Personal__id_tar__0519C6AF", "Tareas")>
    Public Property Tareas() As Tareas
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Tareas)("MascotaModel.FK__Personal__id_tar__0519C6AF", "Tareas").Value
        End Get
        Set
            CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Tareas)("MascotaModel.FK__Personal__id_tar__0519C6AF", "Tareas").Value = value
        End Set
    End Property
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <BrowsableAttribute(False)>
    <DataMemberAttribute()>
    Public Property TareasReference() As EntityReference(Of Tareas)
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Tareas)("MascotaModel.FK__Personal__id_tar__0519C6AF", "Tareas")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedReference(Of Tareas)("MascotaModel.FK__Personal__id_tar__0519C6AF", "Tareas", value)
            End If
        End Set
    End Property

    #End Region

End Class

''' <summary>
''' No Metadata Documentation available.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="MascotaModel", Name:="Raza")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class Raza
    Inherits EntityObject
    #Region "Factory Method"

    ''' <summary>
    ''' Create a new Raza object.
    ''' </summary>
    ''' <param name="id_raza">Initial value of the id_raza property.</param>
    Public Shared Function CreateRaza(id_raza As Global.System.Int32) As Raza
        Dim raza as Raza = New Raza
        raza.id_raza = id_raza
        Return raza
    End Function

    #End Region

    #Region "Primitive Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property id_raza() As Global.System.Int32
        Get
            Return _id_raza
        End Get
        Set
            If (_id_raza <> Value) Then
                Onid_razaChanging(value)
                ReportPropertyChanging("id_raza")
                _id_raza = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("id_raza")
                Onid_razaChanged()
            End If
        End Set
    End Property

    Private _id_raza As Global.System.Int32
    Private Partial Sub Onid_razaChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub Onid_razaChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property descripcion() As Global.System.String
        Get
            Return _descripcion
        End Get
        Set
            OndescripcionChanging(value)
            ReportPropertyChanging("descripcion")
            _descripcion = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("descripcion")
            OndescripcionChanged()
        End Set
    End Property

    Private _descripcion As Global.System.String
    Private Partial Sub OndescripcionChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OndescripcionChanged()
    End Sub

    #End Region

    #Region "Navigation Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("MascotaModel", "FK__Mascotas__id_raz__1BFD2C07", "Mascotas")>
     Public Property Mascotas() As EntityCollection(Of Mascotas)
        Get
            Return CType(Me,IEntityWithRelationships).RelationshipManager.GetRelatedCollection(Of Mascotas)("MascotaModel.FK__Mascotas__id_raz__1BFD2C07", "Mascotas")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedCollection(Of Mascotas)("MascotaModel.FK__Mascotas__id_raz__1BFD2C07", "Mascotas", value)
            End If
        End Set
    End Property

    #End Region

End Class

''' <summary>
''' No Metadata Documentation available.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="MascotaModel", Name:="Tareas")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class Tareas
    Inherits EntityObject
    #Region "Factory Method"

    ''' <summary>
    ''' Create a new Tareas object.
    ''' </summary>
    ''' <param name="id_tarea">Initial value of the id_tarea property.</param>
    Public Shared Function CreateTareas(id_tarea As Global.System.Int32) As Tareas
        Dim tareas as Tareas = New Tareas
        tareas.id_tarea = id_tarea
        Return tareas
    End Function

    #End Region

    #Region "Primitive Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property id_tarea() As Global.System.Int32
        Get
            Return _id_tarea
        End Get
        Set
            If (_id_tarea <> Value) Then
                Onid_tareaChanging(value)
                ReportPropertyChanging("id_tarea")
                _id_tarea = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("id_tarea")
                Onid_tareaChanged()
            End If
        End Set
    End Property

    Private _id_tarea As Global.System.Int32
    Private Partial Sub Onid_tareaChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub Onid_tareaChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property descripcion_tarea() As Global.System.String
        Get
            Return _descripcion_tarea
        End Get
        Set
            Ondescripcion_tareaChanging(value)
            ReportPropertyChanging("descripcion_tarea")
            _descripcion_tarea = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("descripcion_tarea")
            Ondescripcion_tareaChanged()
        End Set
    End Property

    Private _descripcion_tarea As Global.System.String
    Private Partial Sub Ondescripcion_tareaChanging(value As Global.System.String)
    End Sub

    Private Partial Sub Ondescripcion_tareaChanged()
    End Sub

    #End Region

    #Region "Navigation Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("MascotaModel", "FK__Personal__id_tar__0519C6AF", "Personal")>
     Public Property Personal() As EntityCollection(Of Personal)
        Get
            Return CType(Me,IEntityWithRelationships).RelationshipManager.GetRelatedCollection(Of Personal)("MascotaModel.FK__Personal__id_tar__0519C6AF", "Personal")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedCollection(Of Personal)("MascotaModel.FK__Personal__id_tar__0519C6AF", "Personal", value)
            End If
        End Set
    End Property

    #End Region

End Class

''' <summary>
''' No Metadata Documentation available.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="MascotaModel", Name:="Tipo_hogar")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class Tipo_hogar
    Inherits EntityObject
    #Region "Factory Method"

    ''' <summary>
    ''' Create a new Tipo_hogar object.
    ''' </summary>
    ''' <param name="id_tipo_hogar">Initial value of the id_tipo_hogar property.</param>
    Public Shared Function CreateTipo_hogar(id_tipo_hogar As Global.System.Int32) As Tipo_hogar
        Dim tipo_hogar as Tipo_hogar = New Tipo_hogar
        tipo_hogar.id_tipo_hogar = id_tipo_hogar
        Return tipo_hogar
    End Function

    #End Region

    #Region "Primitive Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property id_tipo_hogar() As Global.System.Int32
        Get
            Return _id_tipo_hogar
        End Get
        Set
            If (_id_tipo_hogar <> Value) Then
                Onid_tipo_hogarChanging(value)
                ReportPropertyChanging("id_tipo_hogar")
                _id_tipo_hogar = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("id_tipo_hogar")
                Onid_tipo_hogarChanged()
            End If
        End Set
    End Property

    Private _id_tipo_hogar As Global.System.Int32
    Private Partial Sub Onid_tipo_hogarChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub Onid_tipo_hogarChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property descripcion_tipo_hogar() As Global.System.String
        Get
            Return _descripcion_tipo_hogar
        End Get
        Set
            Ondescripcion_tipo_hogarChanging(value)
            ReportPropertyChanging("descripcion_tipo_hogar")
            _descripcion_tipo_hogar = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("descripcion_tipo_hogar")
            Ondescripcion_tipo_hogarChanged()
        End Set
    End Property

    Private _descripcion_tipo_hogar As Global.System.String
    Private Partial Sub Ondescripcion_tipo_hogarChanging(value As Global.System.String)
    End Sub

    Private Partial Sub Ondescripcion_tipo_hogarChanged()
    End Sub

    #End Region

    #Region "Navigation Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("MascotaModel", "FK__Hogar__id_tipo_h__0EA330E9", "Hogar")>
     Public Property Hogar() As EntityCollection(Of Hogar)
        Get
            Return CType(Me,IEntityWithRelationships).RelationshipManager.GetRelatedCollection(Of Hogar)("MascotaModel.FK__Hogar__id_tipo_h__0EA330E9", "Hogar")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedCollection(Of Hogar)("MascotaModel.FK__Hogar__id_tipo_h__0EA330E9", "Hogar", value)
            End If
        End Set
    End Property

    #End Region

End Class

''' <summary>
''' No Metadata Documentation available.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="MascotaModel", Name:="Usuarios")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class Usuarios
    Inherits EntityObject
    #Region "Factory Method"

    ''' <summary>
    ''' Create a new Usuarios object.
    ''' </summary>
    ''' <param name="usuario">Initial value of the usuario property.</param>
    Public Shared Function CreateUsuarios(usuario As Global.System.String) As Usuarios
        Dim usuarios as Usuarios = New Usuarios
        usuarios.usuario = usuario
        Return usuarios
    End Function

    #End Region

    #Region "Primitive Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property usuario() As Global.System.String
        Get
            Return _usuario
        End Get
        Set
            If (_usuario <> Value) Then
                OnusuarioChanging(value)
                ReportPropertyChanging("usuario")
                _usuario = StructuralObject.SetValidValue(value, false)
                ReportPropertyChanged("usuario")
                OnusuarioChanged()
            End If
        End Set
    End Property

    Private _usuario As Global.System.String
    Private Partial Sub OnusuarioChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnusuarioChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property pass() As Global.System.String
        Get
            Return _pass
        End Get
        Set
            OnpassChanging(value)
            ReportPropertyChanging("pass")
            _pass = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("pass")
            OnpassChanged()
        End Set
    End Property

    Private _pass As Global.System.String
    Private Partial Sub OnpassChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnpassChanged()
    End Sub

    #End Region

    #Region "Navigation Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("MascotaModel", "FK__Adopcion__usuari__2A4B4B5E", "Adopcion")>
     Public Property Adopcion() As EntityCollection(Of Adopcion)
        Get
            Return CType(Me,IEntityWithRelationships).RelationshipManager.GetRelatedCollection(Of Adopcion)("MascotaModel.FK__Adopcion__usuari__2A4B4B5E", "Adopcion")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedCollection(Of Adopcion)("MascotaModel.FK__Adopcion__usuari__2A4B4B5E", "Adopcion", value)
            End If
        End Set
    End Property

    #End Region

End Class

#End Region


